ignore:
  - "examples/"
  - "libsqsh/fuzzer/"
  - "subprojects/"
  - "test/"
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        if_ci_failed: success
        threshold: 30%
