# https://github.com/Gottox/mk
configure:
  - -Dwerror=true
  - -Ddefault_library=static
  - -Dexamples=true
  - -Db_lundef=false
  - -Dtest=true
  - -Ddoc=internal
  - -Dcurl=enabled
  - -Dzlib=enabled
  - -Dlz4=enabled
  - -Dlzma=enabled
  - -Dzstd=enabled
  - -Dfuse=enabled
  - -Dfuse-old=enabled
  - -Db_coverage=true
  - -Db_sanitize=address,undefined
  - -Dtest=extended
  #- -Dfuzzer=true
  #- -Dfuzzer_timeout=10
default:
  - test
env:
  # gdwarf-4 is required to make abi-dumper work
  CFLAGS: -gdwarf-4 -O0 -Og
