name: Check
on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v2
      run: |
        xbps-install -Syu xbps && \
        xbps-install -yu && \
        xbps-install -y base-devel clang libsanitizer-devel zlib-devel \
          liblzma-devel lzo-devel liblz4-devel libzstd-devel fuse3-devel \
          squashfs-tools attr-progs
    - name: install dependencies
      run: apk add alpine-sdk clang curl-dev fuse3-dev lz4-dev xz-dev zstd-dev
    - name: make
      run: make CC=${{ matrix.cc }}
    - name: make check
      run: make check CC=${{ matrix.cc }}
    - name: IRC Message Action
      uses: Gottox/irc-message-action@v2
      if: failure()
      with:
        channel: "Gottox"
        nickname: gh-gottox
        message: "https://github.com/${{ github.repository }} failed on push ${{ github.event.compare }}"
