name: CI
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    container: gottox/hsqs-build
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        CC=clang meson setup /tmp/build \
          -Dcurl=false \
          -Dzlib=true \
          -Dlz4=false\
          -Dlzma=false \
          -Dlzo2=false \
          -Dzstd=false \
          -Dtest=true
    - name: test
      run: |
         ninja -C /tmp/build test
  build:
    runs-on: ubuntu-latest
    container: gottox/hsqs-build
    strategy:
      matrix:
        cc: [gcc, clang]
        all_features: [true, false]
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        CC=${{ matrix.cc }} meson setup /tmp/build \
          -Dcurl=${{ matrix.all_features }} \
          -Dzlib=${{ matrix.all_features }} \
          -Dlz4=${{ matrix.all_features }} \
          -Dlzma=${{ matrix.all_features }} \
          -Dlzo2=${{ matrix.all_features }} \
          -Dzstd=${{ matrix.all_features }}
    - name: build
      run: |
         ninja -C /tmp/build
