name: CI
on:
  push: {}
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  format-check:
    runs-on: ubuntu-latest
    container:
      image: gottox/sqsh-build:x86_64
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        apk add --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing muon
        apk add clang16-extra-tools
        meson setup /tmp/build \
          -Dwerror=true \
          -Dexamples=true  \
          -Dcurl=disabled  \
          -Dzlib=disabled \
          -Dlz4=disabled \
          -Dlzma=disabled  \
          -Dzstd=disabled  \
          -Dthreads=disabled \
          -Dfuse-old=disabled \
          -Dtest=false \
          -Ddoc=false
    - name: muon fmt
      run: |
        if ! find . \( -name meson.build -or -name meson_options.txt \) -print0 \
            | xargs -0 muon fmt -q; then
          find . \( -name meson.build -or -name meson_options.txt \) -print0 \
            | xargs -0 muon fmt -i;
          git diff
          exit 1
        fi
    - name: clang-format
      run: |
        ninja -C /tmp/build clang-format-check
  test:
    needs:
    - format-check
    strategy:
      matrix:
        arch:
          #- i386
          - x86_64
    runs-on: ubuntu-latest
    container:
      image: gottox/sqsh-build:${{ matrix.arch }}
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        apk add zlib-dev lz4-dev xz-dev zstd-dev
        CC=gcc meson setup /tmp/build \
          -Dwerror=true \
          -Dexamples=true  \
          -Dcurl=enabled  \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled  \
          -Dzstd=enabled  \
          -Dthreads=enabled \
          -Dfuse-old=enabled \
          -Dtest=extended \
          -Ddoc=false
    - name: test
      run: |
         ninja -C /tmp/build test

  build:
    needs:
    - format-check
    runs-on: ubuntu-latest
    container: gottox/sqsh-build:${{ matrix.arch }}
    strategy:
      matrix:
        cc:
          - gcc
          - clang
        feature:
          - enabled
          - disabled
        arch:
          #- i386
          - x86_64
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        meson wrap update-db
        CC=${{ matrix.cc }} meson setup /tmp/build \
          -Dwerror=false \
          -Dexamples=true \
          -Dcurl=${{ matrix.feature }} \
          -Dzlib=${{ matrix.feature }} \
          -Dlz4=${{ matrix.feature }} \
          -Dlzma=${{ matrix.feature }} \
          -Dzstd=${{ matrix.feature }} \
          -Dfuse-old=${{ matrix.feature }} \
          -Dtest=false \
          -Ddoc=false
    - name: build
      run: |
        ninja -C /tmp/build

  build-openbsd:
    needs:
    - format-check
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
    steps:
    - uses: actions/checkout@v3
    - uses: "cross-platform-actions/action@v0.19.0"
      with:
        operating_system: openbsd
        architecture: ${{ matrix.arch }}
        version: 7.2
        run: |
          sudo pkg_add git meson squashfs-tools curl lz4 xz zstd
          CC=clang meson setup /tmp/build \
            -Dwerror=true \
            -Dexamples=true \
            -Dcurl=enabled \
            -Dzlib=enabled \
            -Dlz4=enabled \
            -Dlzma=enabled \
            -Dzstd=enabled \
            -Dfuse-old=enabled \
            -Dfuse=disabled \
            -Dtest=extended \
            -Ddoc=false
          # fuse needs root privileges on OpenBSD
          sudo meson test -C /tmp/build -t 5

  build-mac:
    needs:
    - format-check
    runs-on: macos-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
    steps:
    - uses: actions/checkout@v3
    - run: |
          brew install git meson squashfs lz4 xz zstd macfuse
    - run: |
          meson setup /tmp/build \
            -Dwerror=true \
            -Dexamples=true \
            -Dcurl=disabled \
            -Dzlib=enabled \
            -Dlz4=enabled \
            -Dlzma=enabled \
            -Dzstd=enabled \
            -Dfuse-old=enabled \
            -Dfuse=disabled \
            -Dtest=extended \
            -Ddoc=false
    - run: |
          meson test -C /tmp/build -t 5

  doxygen:
    needs:
    - build
    - test
    runs-on: ubuntu-latest
    container: gottox/sqsh-build:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: configure
      run: |
        git config --global --add safe.directory $PWD
        CC=clang meson setup /tmp/build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=disabled \
          -Dzlib=disabled \
          -Dlz4=disabled\
          -Dlzma=disabled \
          -Dzstd=disabled \
          -Dtest=false \
          -Ddoc=true
    - name: generate
      run: |
        cd /tmp/build
        meson compile doc
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref_type == 'tag' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /tmp/build/doc/html
        destination_dir: doxygen
