name: CI
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    container: gottox/sqsh-build
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        CC=clang meson setup /tmp/build \
          -Dcurl=false \
          -Dzlib=true \
          -Dlz4=false\
          -Dlzma=false \
          -Dlzo2=false \
          -Dzstd=false \
          -Dtest=true \
          -Ddoc=false
    - name: test
      run: |
         ninja -C /tmp/build test
  build:
    runs-on: ubuntu-latest
    container: gottox/sqsh-build
    strategy:
      matrix:
        cc: [gcc, clang]
        curl: [true, false]
        zlib: [true, false]
        lz4: [true, false]
        lzma: [true, false]
        lzo2: [true, false]
        zstd: [true, false]
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        CC=${{ matrix.cc }} meson setup /tmp/build \
          -Dcurl=${{ matrix.curl }} \
          -Dzlib=${{ matrix.zlib }} \
          -Dlz4=${{ matrix.lz4 }} \
          -Dlzma=${{ matrix.lzma }} \
          -Dlzo2=${{ matrix.lzo2 }} \
          -Dzstd=${{ matrix.zstd }}
    - name: build
      run: |
         ninja -C /tmp/build
  doxygen:
    needs:
    - build
    - test
    runs-on: ubuntu-latest
    container: gottox/sqsh-build
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        git config --global --add safe.directory $PWD
        CC=clang meson setup /tmp/build \
          -Dcurl=false \
          -Dzlib=true \
          -Dlz4=false\
          -Dlzma=false \
          -Dlzo2=false \
          -Dzstd=false \
          -Dtest=false \
          -Ddoc=true
    - name: generate
      run: |
        cd /tmp/build
        meson compile doc
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /tmp/build/doc/html
