name: CI
on:
- push
jobs:
  test:
    strategy:
      matrix:
        arch:
          #- i386
          - x86_64
    runs-on: ubuntu-latest
    container: gottox/sqsh-build:${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        CC=clang meson setup /tmp/build \
          -Dcurl=false  \
          -Dzlib=true \
          -Dlz4=true \
          -Dlzma=true  \
          -Dlzo2=true  \
          -Dzstd=true  \
          -Dtest=true \
          -Ddoc=false
    - name: test
      run: |
         ninja -C /tmp/build test
  build:
    runs-on: ubuntu-latest
    container: gottox/sqsh-build:${{ matrix.arch }}
    strategy:
      matrix:
        cc:
          - gcc
          - clang
        feature:
          - true
          - false
        arch:
          #- i386
          - x86_64
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        CC=${{ matrix.cc }} meson setup /tmp/build \
          -Dcurl=${{ matrix.feature }} \
          -Dzlib=${{ matrix.feature }} \
          -Dlz4=${{ matrix.feature }} \
          -Dlzma=${{ matrix.feature }} \
          -Dlzo2=${{ matrix.feature }} \
          -Dzstd=${{ matrix.feature }} \
          -Dtest=false \
          -Ddoc=false
    - name: build
      run: |
         ninja -C /tmp/build
  doxygen:
    needs:
    - build
    - test
    runs-on: ubuntu-latest
    container: gottox/sqsh-build:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: configure
      run: |
        git config --global --add safe.directory $PWD
        CC=clang meson setup /tmp/build \
          -Dcurl=false \
          -Dzlib=true \
          -Dlz4=false\
          -Dlzma=false \
          -Dlzo2=false \
          -Dzstd=false \
          -Dtest=false \
          -Ddoc=true
    - name: generate
      if: ${{ github.ref_type == 'tag' }}
      run: |
        cd /tmp/build
        meson compile doc
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref_type == 'tag' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /tmp/build/doc/html
