name: Docker Build utils
on:
  push:
    paths:
      - utils/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.repository }}
        tags: >
          sha-${{ github.sha }} latest
          ${{ github.ref_name }}
        context: utils
        containerfiles: Dockerfile
    - name: Push to Dockerhub
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/gottox
        username: gottox
        password: ${{ secrets.DOCKER_TOKEN }}
